---
title: "reesehs_PeerCommentary_erinea_01."
author: "Reese Hotten-Somers and Erin Anderson"
date: "2023-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Challenges: I had a hard time using the strsplit() command and still am having trouble calling characters out of my character vector.

I also had a lot of trouble with working direcotries and making my working directory a place that is unique to my current repo.

Finally, I struggled with changing df to logical and factor values, and still could use some help with that code.

v<-c("Stately,", "plump", "Buck", "Mulligan", "came", "from", "the", "stairhead", "bearing", "a", "bowl", "of", "lather", "on", "which", "a", "mirror", "and", "a", "razor", "lay", "crossed.")
#this assigns character vector
v1<-("Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.")
#this creates a continuous string
strsplit(v1, split = " ")
#this splits each character 
v[c(3, 6, 9, 12, 15)]
#extracts every third characters from character vector
##reesehs: Hi Erin I really liked how simple you made it to extract every third element. However, I was wondering if you could find a way to create a vector containing only the string that is continous(like v1) and then finding a way to split it like how it is in v? You might be able to do this using str_split where the value is " " because it takes all the spaces and puts another in between them. 
--Also, something that might be helpful for you in order to run code much easier rather than having to copy and paste into the consol is to create chunks! I just looked up a keyboard shortcut online and it's been really helpful in making coding easier and kniting much more pretty!

## Including Plots
a<-m[, 2] 
##reesehs: I'm not sure if it was something weird with the original Rmd file but for some reason there is no matrix here! It seems like you have a really good grasp on how to manipulate them so you might just want to add the matrix back in!
b<-m[,3]
c<-m[,6]
x<-c(a, b, c) 
##reesehs: You might, for efficiency sake, just make a vector that(instead of containing a, b, c) just make it a vector from the matrix and then list 2, 3, 6, which does the same thing. But I think that in more high level question in the future assigning the variables can be helpful in organizing data. You also totally don't have to do this since you good is totally fine!!
#I assigned each column to a variable, "a", "b", or "c" and then assigned x as a character vector comprising of a, b, and c
d<-m[6,]
e<-m[8,]
x<-c(d, e) 
##reesehs: Looks great!
#I used the same method as before to assign rows to individual characters, and then used a character vector to assign both rows to variable x.
g<-m[2,2]
h<-m[6,9]
x<-c(g:h). 
##reesehs: so smart!! I wonder(and I might experiement with this later) if you could just assign x to a vector with in the matrix with 2,2 and 6,9 as the ends of : symbol?
#I used the same method as before, but this time included : to signify I was including all characters from m[2,2] up to and including m[6,9]
z <- strsplit(v1, " ")
#using string split
pick <- z[seq(from = 3, to = 22, by = 3)]
#not sure why this isn't working //reesehs:I'm a little confused by these are here? Maybe they are for challenge 1? Silly code, go back to where you are from!
a <- array(data = 1:400, dim = c(5, 5, 4, 4))
#creating the initial array. 
a[1, 1, 1, 2]
#[1] 101
a[2, 3, 2, ]
#[1]  37 137 237 337
a[1:5, 1:5, 3, 3]
# [,1] [,2] [,3] [,4] [,5]
# [1,]  251  256  261  266  271
# [2,]  252  257  262  267  272
# [3,]  253  258  263  268  273
# [4,]  254  259  264  269  274
# [5,]  255  260  265  270  275 
##NGL I wrote out in words what it returned, but I definitely liked that you just copied what the console spat out, a way more effective explaination!
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae",
    "Daubentoniidae")
Lorisoidea <- c("Lorisidae", "Galagidae")
Strepsirhini <- list(Lemuroidea, Lorisoidea)
names(Strepsirhini) <- list("Lemuroidea", "Lorisoidea")
Strepsirhini
#creates Strepsirhini branch
Tarsioidea <- c("Tarsiidae")
Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Platyrrhini <- c("Cebidae", "Atelidae", "Pitheciidae")
Anthropoidea <- list(Tarsioidea, Catarrhini, Platyrrhini) 
##reesehs: techinically speaking only catarrhini and platyrrhini are in Anthropoidea but that's just kind of semantics I guess!
names(Anthropoidea) <- list("Tarsioidea", "Catarrhini", "Platyrrhini")
#Creates Anthropoidea branch
Haplorhini <- list(Anthropoidea)
#Creates sublist of Anthropoidea
names(Haplorhini) <- list("Anthropoidea")
#WORKSHOP THIS--creates correct list name but adds Anthropoidea to all subsections of the list
##reesehs: I think that's ok, it's essentially saying that (take for instance Cercopithecidae) it is Haplorhini, Anthropoidea, Catarrhini and it ranks them by taxonomic hierarchy. 
Primates <- c("Haplorini", "Strepsirhini")
Primates <- list(Haplorhini, Strepsirhini)
names(Primates) <- list("Haplorhini", "Strepsirhini")
Primates
#WORKSHOP THIS--creates correct phylogency but repeats too many names 
##reesehs: see above comment, also Prof. Schmit said that it wasn't going to look pretty!

##reesehs: make sure to create pretty headings for each of the challenges!! It's the one fun part about coding lol!
m3 <- matrix(data = "3, 0, 1, 23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2", nrow = 5, ncol = 3, byrow = FALSE)
#5x3 matrix row wise
df <- m3
#Made matrix into a data frame
is.logical(df[,2])
#makes the column logical
is.factor(df[,3])
#makes column factor-valued
##reesehs: this looks fabulous!!! Ok, I'm going to leave you with some last notes: 1. add chunks, it is going to save you so much time I promise! 2. create headers to make code more readable! 3. Take everything I say with a hunking chunk of salt, I know very little and I'm getting used to seeing other people's code! Anyways I hope you have a great day and I'll see you on Thursday for class :))
